services:
  postgres:
    image: postgres:16.1-alpine
    container_name: parrot-postgres
    env_file:
      - .env
    ports:
      - "${POSTGRESQL_EXT_PORT}:${DJANGO_DB_PORT}"
    environment:
      - POSTGRES_DB=${DJANGO_DB_NAME}
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASS}
    volumes:
      - parrot-postgres-data:/var/lib/postgresql/data

  dummy-parrot:
    container_name: dummy-parrot
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: 
      - .env
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  parrot-postgres-data:
