services:
  dummy-parrot:
    container_name: dummy-parrot
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file: 
      - .env
    command: >
      sh -c "python manage.py migrate && uwsgi --ini uwsgi.ini"

  db:
    image: postgres:16.1-alpine
    container_name: db
    ports:
      - "${POSTGRESQL_EXT_PORT}:${DJANGO_DB_PORT}"
    environment:
      - POSTGRES_DB=${DJANGO_DB_NAME}
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - parrot-postgres-data:/var/lib/postgresql/data


volumes:
  parrot-postgres-data:
